{% set version = "1.1.2" %}

package:
  name: colorspacious
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/colorspacious/colorspacious-{{ version }}.tar.gz
  sha256: 5e9072e8cdca889dac445c35c9362a22ccf758e97b00b79ff0d5a7ba3e11b618

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - colorspacious

about:
  home: https://github.com/njsmith/colorspacious
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A powerful, accurate, and easy-to-use Python library for doing colorspace conversions

extra:
  recipe-maintainers:
    - kthyng
